name: Authenticate towards GCP
description: Authenticate towards Google Cloud Platform
author: "havard.bakke@pexip.com"

inputs:
  repository:
    required: false
    description: The repository to deploy to
  service_account_key:
    required: false
    description: The GCP service account JSON key used to authenticate towards Google
  service_account:
    required: false
    description: The GCP service account used to authenticate towards Google
  workload_identity_provider:
    required: false
    description: The GCP workload identity provider used to authenticate towards Google

runs:
  using: "composite"
  steps:
    - name: Authenticate towards Google
      if: ${{ inputs.service_account_key != '' }}
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.service_account_key }}

    - name: Authenticate towards Google
      if: ${{ inputs.workload_identity_provider != '' }}
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Setup gcloud SDK
      if: ${{ inputs.repository != '' }}
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker repository
      if: ${{ inputs.repository != '' }}
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.repository }}