name: Production pipeline
on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to run against
        required: true

jobs:
  terraform-deploy:
    runs-on: [self-hosted, linux, X64]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Terraform variables
        shell: bash
        run: |
          echo "TF_VAR_project_id=${{ vars.DEPLOY_PROJECT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_container=${{ needs.docker-build.outputs.tags }}" >> $GITHUB_ENV
      - uses: pexip/shared-github-actions/.github/actions/terraform-deploy-gcp@master
        with:
          directory: ./deploy
          service_account_key: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}