name: Production pipeline
on:
  push:
    branches:
      - master
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment to run against
        required: true

jobs:
  terraform-deploy:
    runs-on: [self-hosted, linux, X64]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Terraform variables
        shell: bash
        run: |
          echo "TF_VAR_project_id=${{ vars.DEPLOY_PROJECT_ID }}" >> $GITHUB_ENV
      - uses: pexip/shared-github-actions/auth-gcp-action@master
        with:
          repository: ${{ vars.DOCKER_REPO }}
          service_account_key: ${{ secrets.DEPLOY_SERVICE_ACCOUNT_KEY }}
      - uses: pexip/shared-github-actions/terraform-deploy-gcp-action@master
        with:
          directory: ./deploy
          token: ${{ secrets.GITHUB_TOKEN }}