name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version (v0.0.0)
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pexip/shared-github-actions/.github/actions/release@master
        with:
          version: ${{ inputs.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jira_webhook: ${{ secrets.jira_webhook }}
          jira_artifact_name: freeswitch-cvp
          jira_project_key: VJ
