name: Build and publish a Docker image
description: Builds and pushes a docker image to a docker repository
author: "havard.bakke@pexip.com"

inputs:
  repository:
    required: true
    description: The repository to deploy to
  image_name:
    required: true
    description: Name of docker image to build and publish
  context:
    required: false
    description: The context to use when building the image
    default: .
  push_image:
    required: false
    description: Should the image be pushed to the repository
    default: true
  tag:
    required: false
    description: Optional tag to apply to the docker image
  dockerfile:
    required: true
    default: ./Dockerfile
    description: The docker file to use when building the image
  token:
    required: false
    description: A token used by the Dockerfile

outputs:
  image:
    description: "Full docker image name"
    value: ${{ steps.metadata.outputs.tags }}
  dockerfile:
    description: "Dockerfile used to build docker image"
    value: ${{ inputs.dockerfile }}

runs:
  using: "composite"
  steps:
    - name: Setup gcloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: "${{ inputs.repository }}/${{ inputs.image_name }}"
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,enable=true,priority=100,prefix=,suffix=,format=long

    - name: Set up Docker Buildx to enable caching
      uses: docker/setup-buildx-action@v3

    - name: Show Dockerfile
      shell: bash
      run: |
        echo ########################################
        echo  Dockerfile: ${{ inputs.dockerfile }}
        echo ########################################
        cat ${{ inputs.dockerfile }}
        echo ########################################

    - name: Build and push Docker image
      env:
        TOKEN:  ${{ inputs.TOKEN }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          TOKEN=${{ inputs.token }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push_image }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}

    - name: Generate job summary
      shell: bash
      run: |
        echo "Built docker image:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Name:  ${{ inputs.repository }}/${{ inputs.image_name }}" >> $GITHUB_STEP_SUMMARY        
        echo "- TAGS: ${{ steps.metadata.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
