name: Build and publish a Docker image to ghcr.io
description: Builds and pushes a docker image to a Github hosted docker repository
author: "havard.bakke@pexip.com"

inputs:
  image_name:
    required: true
    description: Name of docker image to build and publish
  push_image:
    required: false
    description: Should the image be pushed to the repository
    default: true
  tag:
    required: false
    description: Optional tag to apply to the docker image
  dockerfile:
    required: true
    default: ./Dockerfile
    description: The docker file to use when building the image
  github_token:
    required: true
    description: The Github token used to login to the Github Container Registry
  token:
    required: false
    description: A token used by the Dockerfile

outputs:
  image:
    description: "Full docker image name"
    value: ${{ steps.metadata.outputs.tags }}
  dockerfile:
    description: "Dockerfile used to build docker image"
    value: ${{ inputs.dockerfile }}

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v5
      with:
        images: "ghcr.io/${{ inputs.image_name }}"
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,enable=true,priority=100,prefix=,suffix=,format=long

    - name: Set up Docker Buildx to enable caching
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      env:
        TOKEN:  ${{ inputs.TOKEN }}
      uses: docker/build-push-action@v5
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          TOKEN=${{ inputs.token }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push_image }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}

    - name: Generate job summary
      shell: bash
      run: |
        echo "Built docker image:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
        echo "- Name: ghcr.io/${{ inputs.image_name }}" >> $GITHUB_STEP_SUMMARY        
        echo "- TAGS: ${{ steps.metadata.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
