name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pexip/shared-github-actions/.github/actions/release@master
        with:
          version: ${{ inputs.VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
